### PR TITLE
gh-pages update

### PR DESCRIPTION
**Pull request by Rabiawan**
[
    {
        …
    },
    {
      "name": "Rabia",
      "colors": ["#cb202d", "#dc1e28", "#3366cc"]
    }
]

### CODE REVIEW

**Comment by Rabiawan** [comment]
gradient0000

**Comment by Rabiawan** [comment]
gradient0000

**Comment by Rabiawan** [comment]
Rabia

**Comment by SamanIqbal** [comment]
[    
 {       
  …    
 },     
{     
"name": "SI",       
"colors": ["#0e0d0d", "#aa1919"]    
 }
 ]

**Comment by ghosh** [comment]
Please make the change in `gradients.json`

You could read this for help - https://help.github.com/articles/creating-a-pull-request/

**Pull request closed without merging**
