### PR TITLE
New 2 Elements added

### PR DESCRIPTION
**Pull request by subramanya4shenoy**
#Selenium
#Sulphur

### CODE REVIEW

**Comment by ghosh** [comment]
Thanks for contributing so many gradients. These are all so great 😀

**Comment by subramanya4shenoy** [comment]
No Problem :) I will keep updating this. I want this Awesome project to reach a lot of audiences and use it as a directory for gradients.

**Comment by ghosh** [comment]
Umm..not sure. How come you ask?

**Comment by subramanya4shenoy** [comment]
I was trying to access the git for contributing. And got this page.

**Pull request merged**
