### PR TITLE
Swap hex in gradients.json for Mauve + Lush gradients

### PR DESCRIPTION
**Pull request by i-break-codes**
My bad, intention was to render the gradient in this order, had mistakenly reversed them.

### CODE REVIEW

**Comment by Ghosh** [comment]
You actually only need edit the `gradients.json` in the root. The rest gets done via the build process.

**Comment by i-break-codes** [comment]
@Ghosh I was going to commit only gradients.json file, but since you have not added the build files in .gitignore (which we should), so I thought you want to commit the ones which are built to your repo as well.

In this case, we should add `build/scripts/site.js` + `build/styles/site.css`, or am I missing something?

**Comment by Ghosh** [comment]
I cannot add the build folder into the `.gitignore`. uigraidents is hosted via github pages and github cannot run a site out of a folder. The deployment script actually extracts all the code out of the `build` folder and pushes it into the `gh-pages` branch which then becomes the root of the site.

For adding a gradient you really just need to edit only the `gradients.json` file in the root. Its actually all there in the contributing guidelines.

**Comment by i-break-codes** [comment]
@Ghosh Cool, got it, will do the needful.

**Pull request closed without merging**
