### PR TITLE
Added Piglet Gradient

### PR DESCRIPTION
**Pull request by mr-alien**
Added a pig pinkish gradient which goes light pinkish on the right

### CODE REVIEW

**Comment by ArtskydJ** [comment]
Should be `colour` not `color`.

**Comment by mr-alien** [comment]
@ArtskydJ Perhaps both are correct - http://english.stackexchange.com/q/263/ ?

**Comment by mr-alien** [comment]
@ArtskydJ Thanks, changed and weird that we are using `colour` in json instead of `color`

**Comment by Ghosh** [comment]
@mr-alien Feel free to write a PR to change it.

**Comment by ArtskydJ** [comment]
#93...

**Comment by mr-alien** [comment]
@Ghosh Cool, will fix the json and related code soon

**Comment by Ghosh** [comment]
:+1:

**Pull request merged**
